//dictionary for start and their largest Airport code
var dict = {
    "ALABAMA": "BHM","ALASKA": "ANC","ARIZONA": "PHX","ARKANSAS": "LIT","CALIFORNIA": "LAX","COLORADO": "DEN",
    "CONNECTICUT": "BDL", "DELAWARE": "ILG", "FLORIDA": "MIA", "GEORGIA": "ATL", "HAWAII": "HNL", "IDAHO": "BOI",
    "ILLINOIS": "ORD","INDIANA": "IND","IOWA": "DSM","KANSAS": "ICT","KENTUCKY": "CVG","LOUISIANA": "MSY",
    "MAINE": "PWM","MARYLAND": "BWI","MASSACHUSETTS": "BOS","MICHIGAN": "DTW","MINNESOTA": "MSP","MISSISSIPPI": "JAN",
    "MISSOURI": "STL","MONTANA": "BZN","NEBRASKA": "OMA","NEVADA": "LAS","NEW HAMPSHIRE": "MHT","NEW JERSEY": "EWR",
    "NEW MEXICO": "ABQ","NEW YORK": "JFK","NORTH CAROLINA": "CLT","NORTH DAKOTA": "FAR","OHIO": "CLE","OKLAHOMA": "OKC",
    "OREGON": "PDX","PENNSYLVANIA": "PHL","RHODE ISLAND": "PVD","SOUTH CAROLINA": "CHS","SOUTH DAKOTA": "FSD",
    "TENNESSEE": "BNA","TEXAS": "DFW","UTAH": "SLC","VERMONT": "BTV","VIRGINIA": "DCA","WASHINGTON": "SEA",
    "WEST VIRGINIA": "CRW","WISCONSIN": "MKE","WYOMING": "JAC"
};

var one = dict.ALABAMA;
