ALTER TABLE Item DROP CONSTRAINT FK_Item_Seller;
ALTER TABLE Bid DROP CONSTRAINT FK_Bid_Item;
ALTER TABLE Bid DROP CONSTRAINT FK_Bid_Buyer;

DROP TABLE Buyer;
DROP TABLE Seller;
DROP TABLE Item;
DROP TABLE Bid;